### ISSUE TITLE
python2.7  ImportError: No module named entities

### ISSUE THREAD

**Issue by l123456789jy** [aaronsw/html2text#120]
pip install html2text

Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting html2text
  Downloading https://mirrors.aliyun.com/pypi/packages/81/41/0aba42dac6d0ffe0a721f7fe353acc70a4cf284facdb8763f4591961dd0b/html2text-2019.9.26.tar.gz (48kB)
     |████████████████████████████████| 51kB 18.1MB/s 
    ERROR: Command errored out with exit status 1:
     command: /bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g4Ldjw/html2text/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g4Ldjw/html2text/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-g4Ldjw/html2text/pip-egg-info
         cwd: /tmp/pip-install-g4Ldjw/html2text/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g4Ldjw/html2text/setup.py", line 11, in <module>
        version=".".join(map(str, __import__("html2text").__version__)),
      File "html2text/__init__.py", line 3, in <module>
        import html.entities
    ImportError: No module named entities
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by liamengland1** [comment]
https://github.com/aaronsw/html2text/issues/116#issuecomment-412264562
