### ISSUE TITLE
bad end tag error

### ISSUE THREAD

**Issue by eadmaster** [aaronsw/html2text#24]
```
> python html2text.py http://www.hardcoregaming101.net/
Traceback (most recent call last):
  File "C:\SharedPrograms\html2text\html2text.py", line 491, in <module>
    wrapwrite(html2text(data, baseurl))
  File "C:\SharedPrograms\html2text\html2text.py", line 450, in html2text
    return optwrap(html2text_file(html, None, baseurl))
  File "C:\SharedPrograms\html2text\html2text.py", line 445, in html2text_file
    h.feed(html)
  File "C:\PortableApps\Python\Python26\lib\HTMLParser.py", line 108, in feed
    self.goahead(0)
  File "C:\PortableApps\Python\Python26\lib\HTMLParser.py", line 150, in goahead
    k = self.parse_endtag(i)
  File "C:\PortableApps\Python\Python26\lib\HTMLParser.py", line 314, in parse_endtag
    self.error("bad end tag: %r" % (rawdata[i:j],))
  File "C:\PortableApps\Python\Python26\lib\HTMLParser.py", line 115, in error
    raise HTMLParseError(message, self.getpos())
HTMLParser.HTMLParseError: bad end tag: u'</a</p>', at line 416, column 113
```

**Comment by aaronsw** [comment]
This is a bug in Python's HTMLParser. You should probably file it upstream instead:

http://bugs.python.org/
